In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [6]:
a

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

In [23]:
a.shape

(3,)

In [10]:
a.shape

(3,)

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
b.shape

(2, 3)

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [19]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [22]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [24]:
a.dtype

dtype('int32')

In [25]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [26]:
d.dtype

dtype('int16')

In [27]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [28]:
a[0]

1