In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
#array関数・・・配列を生成

In [5]:
print(a)

[1 2 3]


In [6]:
a

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

In [23]:
a.shape

(3,)

In [10]:
a.shape

(3,)

In [11]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
b.shape

(2, 3)

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

In [12]:
c2 = c1.reshape((2, 3))
#reshape関数・・・指定した行列に変換（ビュー）
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
c3 = c2.ravel()
#ravel関数・・・１次元配列化（ビュー）
c3

array([0, 1, 2, 3, 4, 5])

In [14]:
c4 = c2.flatten()
#flatten関数・・・１次元配列化（コピー、新たなメモリ確保が必要）
c4

array([0, 1, 2, 3, 4, 5])

In [24]:
a.dtype

dtype('int32')

In [25]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

In [26]:
d.dtype

dtype('int16')

In [27]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [28]:
a[0]

1

In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

b = np.array([1, 2, 3])
print(b)

print(a[-1:, [1,2]], b.dtype)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[5 6]] int32


In [5]:
import numpy as np
a = np.arange(1, 10, 3)
#arrange関数・・・1～10の間で3とばしの配列をつくる
print(a)

b = np.eye(5)
#eye関数・・・5*5の単位行列を作る
print(b)

print(a[-1], b[2,2])

[1 4 7]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
7 1.0


In [7]:
import numpy as np
a = np.full((1, 5), np.e).T.ravel()
#Full関数：配列の生成（1x5の行列を作成する）
#T・・・配列の倒置
#ravel・・・１次元化
print(a)

b = np.linspace(0, 1, 5)
#Linspace関数：0～1までを5つに分割した関数を生成する
print(b)

c = np.hstack([a, b])
#hstack関数：配列aとbを結合する
print(c)

print(a[-1], c[-1])

[2.71828183 2.71828183 2.71828183 2.71828183 2.71828183]
[0.   0.25 0.5  0.75 1.  ]
[2.71828183 2.71828183 2.71828183 2.71828183 2.71828183 0.
 0.25       0.5        0.75       1.        ]
2.718281828459045 1.0


In [8]:
import numpy as np
a = np.array([1, 3])
b = np.array([-1, 5])
c = np.array([[1, 2], [3, 4]])
d = a @ b
#@はaとbのドット積を算出する
# 1*(-1)+3*5

e = np.dot(c, a)
#dot関数・・・cとaのドット積を算出する


print(d, e)

14 [ 7 15]
